### ISSUE TITLE
[Feature Request]: Ability to specify blurhash and have that be set as the background while loading the image

### ISSUE THREAD

**Issue by Kara-Zor-El** [rodrigobastosv/fancy-shimmer-image#15]
Hi,

I am so grateful to your project as its been amazing but one thing I would love to see is the ability to take a blur hash and be able to have it be the background. There are packages like https://pub.dev/packages/flutter_blurhash and such that you could use to potentially pull this off. Thanks for your amazing package though

**Comment by rodrigobastosv** [comment]
Hey @Kara-Zor-El , thanks a lot for using this package and for the feedback. Could you give me some clarifications on this feature request?

What you are expecting is using the Blur Hash as opposed to using the shimmer right? Or you're expecting to use the shimmer with the Blur hash colors? I'm not sure that last option is feasible.

I could for sure implement the first option, but my only concern is, by doing that i may deviate a little bit the purpose of this package. People would be using them for the Blur instead of for the shimmering.

Do you have any thoughts around that?

Again, thanks a lot!
